# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui\ScannerView.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScannerView(object):
    def setupUi(self, ScannerView):
        ScannerView.setObjectName("ScannerView")
        ScannerView.resize(1062, 742)
        self.horizontalLayout: QtWidgets.QHBoxLayout
        self.horizontalLayout = QtWidgets.QHBoxLayout(ScannerView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout: QtWidgets.QGridLayout
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableView: QtWidgets.QTableView
        self.tableView = QtWidgets.QTableView(ScannerView)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.Scanner: QtWidgets.QLabel
        self.Scanner = QtWidgets.QLabel(ScannerView)
        self.Scanner.setObjectName("Scanner")
        self.gridLayout.addWidget(self.Scanner, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(ScannerView)
        QtCore.QMetaObject.connectSlotsByName(ScannerView)

    def retranslateUi(self, ScannerView):
        _translate = QtCore.QCoreApplication.translate
        ScannerView.setWindowTitle(_translate("ScannerView", "Form"))
        self.Scanner.setText(_translate("ScannerView", "Scanner"))
